## Import libs

In [1]:
from math import sqrt, isnan
from pathlib import Path

import tensorflow as tf
from tensorflow.keras.optimizers import Adam, Adagrad
from tensorflow.data import Dataset

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from util import metrics
from util.load_data import load_data
from util.evaluation import *

In [2]:
from experiment.models import Generator2
from experiment.models import Discriminator2
from experiment.learning import *

## Preliminaries

In [3]:
batch_size = 64
epochs = 10
#learning_rate = 0.001
#ae_opt = Adam(learning_rate=learning_rate)

In [4]:
learning_rate = 0.0001
beta_1 = 0.5
gen_opt = Adam(learning_rate=learning_rate, beta_1=beta_1)
disc_opt = Adam(learning_rate=learning_rate, beta_1=beta_1)
d2_opt = Adam(learning_rate=learning_rate)

## Load data

In [5]:
x_train, y_train, a_train = load_data('adult', 'train')
raw_data = (x_train, y_train, a_train)

In [6]:
x_train[:,-1]

array([0., 0., 0., ..., 1., 0., 0.])

In [7]:
'''For the FairGAN model our vector X must not include the protected atribute'''
x_train = x_train[:,:-1]

In [8]:
#a_train.reshape(24128,)

In [9]:
#any(x_train[:,-1] - a_train.reshape(24128,))

In [10]:
xdim = x_train.shape[1]
ydim = y_train.shape[1]
adim = a_train.shape[1]
noise_dim = xdim + ydim

In [11]:
xdim

111

In [12]:
x_train[0]

array([0.        , 0.        , 0.        , 1.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 1.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 1.        , 0.        ,
       0.        , 0.        , 1.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 1.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 1.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 1.        , 0.        , 0.37901745, 0.39795918,
       0.        , 0.        , 0.        , 0.        , 0.     

In [13]:
y_train[0]

array([0.])

In [14]:
a_train[0]

array([0.])

In [15]:
train_data = Dataset.from_tensor_slices((x_train, y_train, a_train))
train_data = train_data.batch(batch_size, drop_remainder=True)
train_data

<BatchDataset shapes: ((64, 111), (64, 1), (64, 1)), types: (tf.float64, tf.float64, tf.float64)>

In [16]:
x_valid, y_valid, a_valid = load_data('adult', 'valid')
x_valid = x_valid[:,:-1]

valid_data = Dataset.from_tensor_slices((x_valid, y_valid, a_valid))
valid_data = valid_data.batch(batch_size, drop_remainder=True)

In [17]:
x_test, y_test, a_test = load_data('adult', 'test')

test_data = Dataset.from_tensor_slices((x_test, y_test, a_test))
test_data = test_data.batch(batch_size, drop_remainder=True)

# Aqui to fazendo testes pra ver se consigo contruir uma fairgan constuindo aos poucos

In [18]:
gen = Generator2(xdim, ydim, adim)
disc = Discriminator2(xdim, ydim, adim)

train_loop(gen, disc, train_data, batch_size, noise_dim, epochs=10, gen_opt=gen_opt, disc_opt=disc_opt, d2_opt=None)

> Epoch | G Loss | Disc Loss
> 1 | 0.6601474285125732 | 1.3970037698745728
> 2 | 0.6931471824645996 | 1.3862943649291992
> 3 | 0.6931471824645996 | 1.3862943649291992
> 4 | 0.6931471824645996 | 1.3862943649291992
> 5 | 0.6931471824645996 | 1.3862943649291992
> 6 | 0.6931471824645996 | 1.3862943649291992
> 7 | 0.6931471824645996 | 1.3862943649291992
> 8 | 0.6931471824645996 | 1.3862943649291992
> 9 | 0.6931471824645996 | 1.3862943649291992
> 10 | 0.6931471824645996 | 1.3862943649291992


In [19]:
gen_data = []

for X, Y, A in train_data:
    noise = tf.random.normal([batch_size, noise_dim])
    batch_gen_data = gen(noise, A, batch_size)
    gen_data.append(batch_gen_data)

In [20]:
gen_data

[<tf.Tensor: shape=(64, 113), dtype=float32, numpy=
 array([[0.02046856, 0.04046933, 0.0310139 , ..., 0.0193625 , 0.28215382,
         0.        ],
        [0.0203794 , 0.04032784, 0.03089497, ..., 0.01927686, 0.28193578,
         0.        ],
        [0.02042324, 0.040397  , 0.03095337, ..., 0.01931899, 0.2820274 ,
         0.        ],
        ...,
        [0.02043577, 0.04041675, 0.03096999, ..., 0.01933096, 0.28205818,
         0.        ],
        [0.02037446, 0.04031988, 0.03088838, ..., 0.01927203, 0.28192365,
         0.        ],
        [0.02045562, 0.04044862, 0.03099656, ..., 0.01935003, 0.28212208,
         0.        ]], dtype=float32)>,
 <tf.Tensor: shape=(64, 113), dtype=float32, numpy=
 array([[0.02039037, 0.04034516, 0.03090959, ..., 0.01928733, 0.28196278,
         0.        ],
        [0.02043181, 0.04041088, 0.03096486, ..., 0.01932718, 0.2820639 ,
         0.        ],
        [0.02024111, 0.04010763, 0.03071004, ..., 0.01914384, 0.2815802 ,
         1.        ],
 

In [21]:
tensor_gen_data = tf.convert_to_tensor(gen_data)
tensor_gen_data

<tf.Tensor: shape=(377, 64, 113), dtype=float32, numpy=
array([[[0.02046856, 0.04046933, 0.0310139 , ..., 0.0193625 ,
         0.28215382, 0.        ],
        [0.0203794 , 0.04032784, 0.03089497, ..., 0.01927686,
         0.28193578, 0.        ],
        [0.02042324, 0.040397  , 0.03095337, ..., 0.01931899,
         0.2820274 , 0.        ],
        ...,
        [0.02043577, 0.04041675, 0.03096999, ..., 0.01933096,
         0.28205818, 0.        ],
        [0.02037446, 0.04031988, 0.03088838, ..., 0.01927203,
         0.28192365, 0.        ],
        [0.02045562, 0.04044862, 0.03099656, ..., 0.01935003,
         0.28212208, 0.        ]],

       [[0.02039037, 0.04034516, 0.03090959, ..., 0.01928733,
         0.28196278, 0.        ],
        [0.02043181, 0.04041088, 0.03096486, ..., 0.01932718,
         0.2820639 , 0.        ],
        [0.02024111, 0.04010763, 0.03071004, ..., 0.01914384,
         0.2815802 , 1.        ],
        ...,
        [0.02032306, 0.04023805, 0.03081964, ..., 0.

In [22]:
x_gen = tensor_gen_data[:,:,:-2]
y_gen = tensor_gen_data[:,:,-2]
a_gen = tensor_gen_data[:,:,-1]

In [23]:
#x_gen

In [24]:
num_batches = x_gen.shape[0]
new_shape = num_batches*batch_size

In [25]:
x_gen = tf.reshape(x_gen,shape=(new_shape, xdim))
y_gen = tf.reshape(y_gen,shape=(new_shape, ydim))
a_gen = tf.reshape(a_gen,shape=(new_shape, adim))

In [26]:
a_gen

<tf.Tensor: shape=(24128, 1), dtype=float32, numpy=
array([[0.],
       [0.],
       [0.],
       ...,
       [0.],
       [1.],
       [0.]], dtype=float32)>

In [27]:
unbatched_train = train_data.unbatch()
unbatched_train = list(unbatched_train.as_numpy_iterator())

x, y, a = [], [], []

for row in unbatched_train:
    x.append(row[0])
    y.append(row[1])
    a.append(row[2])


In [28]:
x = tf.convert_to_tensor(x)
y = tf.convert_to_tensor(y)
a = tf.convert_to_tensor(a)

In [29]:
def euclidian_dist(real_data, gen_data, conditional=False):

        '''if conditional:
        a0_filter4real_data = filtering(mask=1-real_data[1], data=real_data[0])
        a0_filter4gen_data = filtering(mask=1-gen_data[1], data=gen_data[0])

        a1_filter4real_data = filtering(mask=real_data[1], data=real_data[0])
        a1_filter4gen_data = filtering(mask=gen_data[1], data=gen_data[0])
        
        ed4a0 = euclidian_dist(a0_filter4real_data, a0_filter4gen_data)
        ed4a1 = euclidian_dist(a1_filter4real_data, a1_filter4gen_data)
        
        return (ed4a0, ed4a1)'''

    #else:
        real_data = tf.dtypes.cast(real_data, tf.double)
        gen_data = tf.dtypes.cast(gen_data, tf.double)

        if real_data.shape[0] > gen_data.shape[0]:
            real_data = real_data[:gen_data.shape[0]]
        elif real_data.shape[0] < gen_data.shape[0]:
            gen_data = gen_data[:real_data.shape[0]]
        else:
            pass

        '''return tf.sqrt(
                    tf.math.reduce_sum(
                        tf.math.squared_difference(real_data, gen_data)))'''
        return tf.norm((real_data- gen_data), ord='euclidean')

In [30]:
xy = metrics.euclidian_dist(tf.concat((x, y), 1), tf.concat((x_gen, y_gen), 1))
print(xy)
xya = metrics.euclidian_dist(tf.concat((x, y, a), 1), tf.concat((x_gen, y_gen, a_gen), 1))
print(xya)
cond_a0, cond_a1 = metrics.euclidian_dist((tf.concat((x, y), 1), a), (tf.concat((x_gen, y_gen), 1), a_gen), conditional=True)
print(cond_a0, cond_a1)

tf.Tensor(364.35364031473983, shape=(), dtype=float64)
tf.Tensor(364.3536403147399, shape=(), dtype=float64)
tf.Tensor(294.59933754089, shape=(), dtype=float64) tf.Tensor(214.3940426669351, shape=(), dtype=float64)
